# Generated by Django 5.0.2 on 2024-05-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevents',
            name='image',
            field=models.ImageField(upload_to='static/uploads'),
        ),
    ]
