# Generated by Django 5.0.2 on 2024-05-22 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_upcomingevents_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.upcomingevents')),
            ],
            options={
                'verbose_name': 'Past event',
                'verbose_name_plural': 'Past events',
            },
        ),
    ]
