# Generated by Django 5.0.2 on 2024-06-02 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_concludedevents_delete_pastevents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concludedevents',
            options={'verbose_name': 'Concluded event', 'verbose_name_plural': 'Concluded events'},
        ),
        migrations.AlterModelOptions(
            name='upcomingevents',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrant_name', models.CharField(max_length=250)),
                ('registrant_email', models.EmailField(max_length=250)),
                ('registrant_phone_number', models.CharField(max_length=25)),
                ('additional_message', models.CharField(blank=True, max_length=250, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.upcomingevents')),
            ],
        ),
    ]
