# Generated by Django 5.0.2 on 2024-06-26 16:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_concludedevents_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventregistration",
            options={
                "verbose_name": "Registered person",
                "verbose_name_plural": "registered persons",
            },
        ),
        migrations.AlterModelOptions(
            name="upcomingevents",
            options={
                "ordering": ("-date", "-time"),
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="additional_message",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="upcomingevents",
            name="image",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="eventregistration",
            constraint=models.UniqueConstraint(
                fields=("event_id", "registrant_email", "registrant_phone_number"),
                name="Duplicated registration",
                violation_error_message="Duplicate registration",
            ),
        ),
    ]
